[project]
name = "Chronicle"
version = "0.1.0"
requires-python = ">=3.10"
description = "A local first developer intelligence tool"
dependencies = [
    "typer>=0.16"
]

[build-system]
requires = ['setuptools>=68',]
build-backend = "setuptools.build_meta"

[project.scripts]
chronicle = "chronicle.cli.main:main"

[tool.setuptools.packages.find]
where = ["src"]